### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Sharparam** [ZjMNZHgG5jMXw/kauthesis#2]
The project does not compile using the provided `INSTALL` file, it complains about a checksum not passing as shown in [this gist](https://gist.github.com/Sharparam/f7fd9cb9e8d3d2ccfe8965149a7466a3).

I'm running 64-bit Arch linux with the latest TeXLive package.

`latex --version` returns:

```
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Arch Linux)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.24; using libpng 1.6.26
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.46.0
```

It seems the actual package compiles fine but the documentation fails. ~~The installation script is referencing a directory `kauguide` that doesn't actually exist in the repo, perhaps this is related to the error?~~ Nevermind, `kauguide.tex` is a file.

**Comment by ZjMNZHgG5jMXw** [comment]
Hi Adam,

I missed to adjust the checksum in the kautools.dtx after recent changes. This is now done in aba8db2fb3b1f87ad3df5335693d69e55ef0febb.

Thanks for pointing out!

Cheers,
Stefan.

**Comment by ZjMNZHgG5jMXw** [comment]
Did it work? If so, please close the issue.

**Comment by Sharparam** [comment]
Pulled the changes and now it installs successfully complete with the documentation!

Unrelated to this issue but is the KAU logo supposed to be shown in any of the templates? There are some references to `kau-logo-tryck` but it's not included from what I've seen.

Edit: Also, with the `kaumasters` class, page numbering starts on 3 (iii). Maybe I should create an issue for it.

Edit 2: Made an issue about the logo missing: #3
